---
# splunk> related variables used in development.
# please alter them to your needs using a copy of the entire "inventories/development" folder
splunk_user: splunk
splunk_uid: 2000
splunk_group: splunk
splunk_gid: 2000
splunk_user_home: /home/splunk
splunk_user_shell: /usr/bin/bash
splunk_user_profile: .bash_profile

splunk_home: /opt/splunk
splunk_home_fs: /
splunk_home_free: 6000000000
